### PR TITLE
Coding minor update

### PR DESCRIPTION
**Pull request by cyfung1031**
some coding improvement is made without any affect to the function or features provided in this script.

### CODE REVIEW

**Comment by cyfung1031** [comment]
@CoinkWang

**Comment by CoinkWang** [comment]
LGTM

**Comment by cyfung1031** [comment]
> LGTM

@CoinkWang 

I found that the subtitle translation is having some problems..

https://www.youtube.com/watch?v=M2cckDmNLMI

Choose Japanese subtitle and translate to English.

Screen Shot 2022-12-25 at 23 07 18

0:23 is still okay, although the end of the sentence should not end with "it's"

Screen Shot 2022-12-25 at 23 07 35

0:30 the translation get broken.

Screen Shot 2022-12-25 at 23 07 46

0:33 completely no translation...

**Comment by CoinkWang** [comment]
@cyfung1031 I found that the offical timed texts are broken, any good ideas? I'm afraid it's hard to fix by this proj.

**Comment by cyfung1031** [comment]
@CoinkWang 

I found that in https://greasyfork.org/en/scripts/456108, it uses Google's translation api which is quite good.

`https://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=en&dj=1&dt=t&dt=rm&q=XXXXXXXXXXXXX`

It can translate a very long text as well. In that Userscript, he translate the entire description content at once.

`sl=auto` means the original lang is detected by the api
`tl=en` is the target lang for translation.

I guess you can modify this script like this.

get the `defaultJson` first. 
extract its texts in that json object. join by `\n` (be careful if the text lines already contain \n)

ask Google's translation api to help
get the json response and then line by line put back to `defaultJson`

**Comment by cyfung1031** [comment]
> @CoinkWang
> 
> I found that in https://greasyfork.org/en/scripts/456108, it uses Google's translation api which is quite good.
> 
> `https://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=en&dj=1&dt=t&dt=rm&q=XXXXXXXXXXXXX`
> 
> It can translate a very long text as well. In that Userscript, he translate the entire description content at once.
> 
> `sl=auto` means the original lang is detected by the api `tl=en` is the target lang for translation.
> 
> I guess you can modify this script like this.
> 
> get the `defaultJson` first. extract its texts in that json object. join by `\n` (be careful if the text lines already contain \n)
> 
> ask Google's translation api to help get the json response and then line by line put back to `defaultJson`

@CoinkWang  see PR https://github.com/CoinkWang/Y2BDoubleSubs/pull/18

**Pull request merged**
